
resources:
  # - ./gateway-api.yaml
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
  # - https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.crds.yaml
  # - https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.yaml
  - ./istio.yaml
  - ./cert-manager.yaml