apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: be
  name: tao-portal-be
spec:
  selector:
    matchLabels:
      tier: be 
  template:
    metadata:
      labels:
        tier: be
    spec:
      containers:
      - image: tao/portal/backend
        resources: {}
        name: backend
        envFrom:
        - secretRef:
            name: tao-portal-be-env
        ports:
        - containerPort: 3000
          protocol: TCP
          name: http
      - image: tao/portal/backend
        resources: {}
        name: worker
        envFrom:
        - secretRef:
            name: tao-portal-worker-env
        command:
        - node
        - './worker.js'
      restartPolicy: Always

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: tao-portal-be-grades-ready
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: tao/portal/backend
            resources: {}
            name: worker
            envFrom:
            - secretRef:
                name: tao-portal-worker-env
            command:
            - node
            - './src/jobs/gradesReadyJob.js'
          restartPolicy: Never

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: tao-portal-be-grades-notif
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: tao/portal/backend
            resources: {}
            name: worker
            envFrom:
            - secretRef:
                name: tao-portal-worker-env
            command:
            - node
            - './src/notifications/gradesNotificationJob.js'
          restartPolicy: Never

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: tao-portal-be-processor
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: tao/portal/backend
            resources: {}
            name: worker
            envFrom:
            - secretRef:
                name: tao-portal-worker-env
            command:
            - node
            - './processor.js'
          restartPolicy: Never
          
---

apiVersion: v1
kind: Service
metadata:
  name: tao-portal-be
  labels: &labels
    tier: be
spec:
  selector: *labels
  ports:
  - port: 3000
    targetPort: 3000
