apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/construct/manifests

images:
  - name: tao/construct/backend
    newName: quay.io/tao-ce/construct/backend
    newTag: latest
  - name: tao/construct/frontend
    newName: quay.io/tao-ce/construct/frontend
    newTag: latest