---
apiVersion: "gateway.networking.k8s.io/v1"
kind: "HTTPRoute"
metadata:
  name: "tao-ce-tao-deliver-fe-static"
spec:
  parentRefs:
  - name: gateway
    namespace: istio-system
  rules:
  - backendRefs:
    - name: "tao-ce-tao-deliver-fe-static"
      port: 8080
    # filters:
    # - type: "URLRewrite"
    #   urlRewrite:
    #     path:
    #       replacePrefixMatch: "/"
    #       type: "ReplacePrefixMatch"
    matches:
    - path:
        type: "PathPrefix"
        value: "/deliver-fe-static"
  - backendRefs:
    - name: "tao-ce-tao-deliver-fe-static"
      port: 8080
    matches:
    - path:
        type: "PathPrefix"
        value: "/sw.js"