apiVersion: apps/v1
kind: Deployment
metadata:
  labels: &labels
    service: pubsub
    tier: api
  name: service-pubsub-api
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - image: services/pubsub/emulator
        resources: {}
        name: emulator
        env:
        - name: PUBSUB_PORT
          value: "8432"
      - image: services/pubsub/ui
        resource: {}
        name: ui
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: service-pubsub-api
  labels: &labels
    service: pubsub
    tier: api  
spec:
  selector: *labels
  ports:
  - port: 8432
    targetPort: 8432
    name: api

