
namePrefix: tao-ce-

labels:
  - pairs:
      app: tao-ce
      component: deliver
    includeSelectors: true
    includeTemplates: true
    
resources:
- ./deployments/be.yaml
- ./deployments/sandbox.yaml
- ./deployments/static.yaml
- ./deployments/bootstrap.yaml
# - ./secrets/deliver-be-env.yaml
# - ./secrets/deliver-fe-bootstrap-env.yaml
# - ./secrets/deliver-fe-static-env.yaml
- ./routes/deliver-sandbox.yaml
- ./routes/deliver-fe-bootstrap.yaml
- ./routes/deliver-fe-static.yaml


secretGenerator:
  - name: tao-deliver-fe-static-config
    files:
    - ./files/Caddyfile

configurations:
  - ./backendRefs.yaml

