apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: tao-ce-

labels:
- pairs:
    app: tao-ce
    component: backoffice
  includeSelectors: true
  includeTemplates: true

resources:
- ./secret.yaml
- ./deploy.yaml
- ./route.yaml

configurations:
  - ./backendRefs.yaml

