---
apiVersion: "gateway.networking.k8s.io/v1"
kind: "HTTPRoute"
metadata:
  name: "tao"
spec:
  # hostnames:
  # - community.tao.internal
  parentRefs:
  - name: gateway
    namespace: istio-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /backoffice
    backendRefs:
    - name: tao
      port: 8080
 