apiVersion: "v1"
kind: "Secret"
metadata:
  name: "tao-env"
stringData:
  DELIVERTENANT_0_CUSTOMER_ID: "2"
  DELIVERTENANT_0_ID: "1"
  DELIVERTENANT_0_LABEL: "OAT TAO Solar Test Runner"
  DELIVERTENANT_0_LTI_1P3_AUDIENCE_URL: "https://community.tao.internal/backoffice"
  DELIVERTENANT_0_LTI_1P3_CREDENTIALS_0_CLIENT_ID: "backoffice-deliver-id"
  DELIVERTENANT_0_LTI_1P3_CREDENTIALS_0_JWKS: "http://tao-ce-em-auth-server:8080/.well-known/jwks.json"
  DELIVERTENANT_0_LTI_1P3_CREDENTIALS_COUNT: "1"
  DELIVERTENANT_0_LTI_1P3_LAUNCH_URL: "https://community.tao.internal/deliver/api/v1/auth/launch-lti-1p3"
  DELIVERTENANT_0_LTI_1P3_OIDC_LOGIN_INITIATION_URL: "https://community.tao.internal/auth-server/lti1p3/oidc/initiation"
  DELIVERTENANT_0_OAUTH_CREDENTIALS_0_KEY: "backoffice-deliver-id"
  DELIVERTENANT_0_OAUTH_CREDENTIALS_0_ROLES_0: "Learner"
  DELIVERTENANT_0_OAUTH_CREDENTIALS_0_ROLES_1: "ContentDeveloper"
  DELIVERTENANT_0_OAUTH_CREDENTIALS_0_ROLES_COUNT: "2"
  DELIVERTENANT_0_OAUTH_CREDENTIALS_0_SECRET: "client-secret"
  DELIVERTENANT_0_OAUTH_CREDENTIALS_COUNT: "1"
  DELIVERTENANT_0_ROOT_URL: "http://tao-ce-tao-deliver-be:80/api/v1/"
  DELIVERTENANT_0_TOKEN_URL: "http://tao-ce-em-auth-server:8080/v1/oauth2/tokens"
  DELIVERTENANT_COUNT: "1"
  ELASTICSEARCH_HOSTS: "http://es.deps.internal:9200"
  FEATURE_FLAG_ENABLE_DATA_STORE_STORAGE: "true"
  FEATURE_FLAG_FLA: "true"
  # FEATURE_FLAG_QUICK_WINS_ENABLED: "true"
  # FEATURE_FLAG_STATISTIC_METADATA_IMPORT: "true"
  # FEATURE_FLAG_TAO_ADVANCE_ONLY: "true"
  # FEATURE_FLAG_TRANSLATION_ENABLED: "true"
  # FEATURE_FLAG_UNIQUE_NUMERIC_QTI_IDENTIFIER: "true"
  GOOGLE_CLOUD_DELIVERY_EXECUTION_PUB_SUB_TOPIC_ID: "ss-delivery-executions-topic"
  GOOGLE_CLOUD_DELIVERY_PUB_SUB_TOPIC_ID: "ss-deliveries-topic"
  GOOGLE_CLOUD_PROJECT: "emulator-project"
  LTI_AUTHORIZATION_SERVER_FACTORY_ENCRYPTION_KEY: "my-key"
  SCORING_CLIENT_ID: "ss-solar-client-id-for-tao"
  SCORING_CLIENT_SECRET: "secret"
  SCORING_ENABLE: "false"
  SCORING_SCOPE: "event:post"
  SCORING_SERVICE_URL: "http://tao-ce-tao-scoring-service-be:8080/api/v1/events"
  SCORING_TOKEN_URL: "http://tao-ce-em-auth-server:8080/v1/oauth2/tokens"
  XDEBUG_MODE: "off"