apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/timers/manifests

images:
  - name: tao/timers/backend
    newName: quay.io/tao-ce/tao/timers/backend
    newTag: latest