apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - construct
 - datastore
 - deliver
 - devkit
 - dynamic-query
 - environment-management
 - hierarchy
 - portal
 - scoring
 - simple-reports
 - task-orchestrator
 - timers