apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/hierarchy/manifests

images:
  - name: tao/hierarchy/backend
    newName: quay.io/tao-ce/tao/hierarchy/backend
    newTag: latest