apiVersion: "v1"
kind: "Secret"
metadata:
  name: "tao-deliver-fe-static-env"
stringData:
  API_URL: "https://community.tao.internal/deliver"
  PATH_PREFIX: "/deliver"
  STATIC_URL: "https://community.tao.internal/deliver-fe-static/"
