apiVersion: "v1"
kind: "Secret"
metadata:
  name: tao-deliver-be-env
  labels:
    up: go
stringData:
  APP_DEBUG: "false"
  APP_DEFAULT_LOCALE: "en-US"
  APP_ENV: "offline"
  APP_SECRET: "954eb3a577baa0228a0133965ab3f1f4"
  ASSETS_MAX_FILE_SIZE_LIMIT: "1M"
  ASSETS_URL_SIGNATURE_KEY: "SecretK3y"
  AUTH_SERVER_TOKEN_REQUEST_URL: "http://tao-ce-em-auth-server:8080/v1/oauth2/tokens"
  BIGTABLE_EMULATOR_HOST: "bigtable.deps.internal:9035"
  COMPOSER_AUTH: "{\"http-basic\":{\"github.com\":{\"username\":\"${GITHUB_USERNAME}\",\"password\":\"${GITHUB_TOKEN}\"}}}"
  # CONTENT_API_URL: "http://tao-ce-tao-content-be:3000"
  COOKIE_DOMAIN_LEVEL_MAX: "2"
  CORS_ALLOW_ORIGIN: ".*"
  DATASTORE_GOOGLE_CLOUD_PROJECT: "emulator-project"
  DATA_STORE_ENABLE_RESULTS_TRANSFER: "true"
  DELIVER_BACKEND_URL: "https://community.tao.internal/deliver"
  DELIVER_FRONTEND_URL: "https://community.tao.internal/deliver-fe"
  DELIVER_LTI_DEEP_LINKING_FRONTEND_URL: "https://community.tao.internal/deep-linking"
  DOCUMENT_MANAGER_TABLE_NAME_BATTERIES: "portal-battery"
  DOCUMENT_MANAGER_TABLE_NAME_BATTERY_DISTRIBUTIONS: "battery-distribution"
  DOCUMENT_MANAGER_TABLE_NAME_DELIVERIES: "test-runner-deliveries"
  DOCUMENT_MANAGER_TABLE_NAME_DELIVERY_EXECUTIONS: "delivery-executions"
  DOCUMENT_MANAGER_TABLE_NAME_DELIVERY_EXECUTIONS_ALIAS: "delivery-executions-alias"
  DOCUMENT_MANAGER_TABLE_NAME_LTI_OAUTH_NONCES: "lti-oauth-nonces"
  DOCUMENT_MANAGER_TABLE_NAME_OAUTH2_ACCESS_TOKEN: "oauth2-access-token"
  DOCUMENT_MANAGER_TABLE_NAME_PUBLICATIONS: "publications"
  DOCUMENT_REDIS_CACHE_NAMESPACE: "deliver-be-local-documents"
  DOCUMENT_REDIS_CACHE_TTL: "0"
  DYNAMIC_QUERY_API_INDEX_BATTERY: "portalBattery"
  DYNAMIC_QUERY_API_INDEX_DELIVERY: "testRunnerDeliveries"
  DYNAMIC_QUERY_API_URL: "http://tao-ce-tao-dynamic-query-api:3000"
  ELASTICSEARCH_HOST: "es.deps.internal"
  ELASTICSEARCH_PORT: "9200"
  ELASTICSEARCH_API_KEY: ''
  EM_AUTH_SERVER_GRPC_GATEWAY_HOST: "http://tao-ce-em-auth-server:8888"
  EM_SIDECAR_HOST: "tao-ce-em-auth-server"
  EM_SIDECAR_PORT: "1888"
  ENQUEUE_DSN: "gps:"
  FIRESTORE_EMULATOR_HOST: "firestore.deps.internal:8080"
  FIRESTORE_PROJECT_ID: "demo-tao"
  GCLOUD_PROJECT: "emulator-project"
  GOOGLE_CLOUD_BIGTABLE_INSTANCE: "emulator-instance"
  GOOGLE_CLOUD_CDN_KEY: ""
  GOOGLE_CLOUD_CDN_KEY_NAME: ""
  GOOGLE_CLOUD_CDN_URL: ""
  GOOGLE_CLOUD_PROJECT: "emulator-project"
  GOOGLE_CLOUD_STORAGE_BUCKET_NAME: ""
  GOOGLE_CLOUD_STORAGE_DATA_STORE_BUCKET_NAME: ""
  GOOGLE_CLOUD_STORAGE_DELIVERY_PROCESSING_INPUT_BUCKET_NAME: ""
  GOOGLE_CLOUD_STORAGE_PREUPLOADED_PACKAGE_BUCKET_NAME: ""
  GOOGLE_CLOUD_STORAGE_SIGNED_URL_TTL: "21600"
  HEALTH_CHECK_PUB_SUB_TOPIC: ""
  LOCK_DSN: "redis://redis.deps.internal:6379"
  LTI1P3_PROCTORING_AUDIENCE: "http://tao-ce-proctoring-lti13-gateway:8080"
  LTI1P3_PROCTORING_CLIENT_ID: "deliver-proctoring-client-id"
  LTI1P3_PROCTORING_DEPLOYMENT_ID: "1"
  LTI_GATEWAY_URL: "http://tao-ce-em-lti-gateway:80"
  MESSENGER_AGS_INITIALIZATION_TRANSPORT_DSN: "gps://default/ags-initialization?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_CLEAN_UP_TRANSPORT_DSN: "gps://default/clean-up?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_CLOSURE_TRANSPORT_DSN: "gps://default/closure?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_DATA_STORE_DELIVERY_EXECUTION_ACTIONS_TRANSPORT_DSN: "gps://default/datastore-delivery-execution-actions?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_DATA_STORE_RESULT_TRANSPORT_DSN: "gps://default/delivery-results-ds?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_DATA_STORE_TRANSPORT_DSN: "gps://default/datastore?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_DELIVERY_EXECUTION_ACS_LOG_TRANSPORT_DSN: "gps://default?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10&topic[name]=acs-log"
  MESSENGER_DELIVERY_EXECUTION_ASSESSMENT_LOG_TRANSPORT_DSN: "gps://default?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10&topic[name]=assessment-log"
  MESSENGER_DELIVERY_EXECUTION_TRANSPORT_DSN: "gps://default?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10&topic[name]=delivery-execution"
  MESSENGER_DELIVERY_EXECUTION_UI_EVENT_TRANSPORT_DSN: "gps://default/ui-events-topic?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_DELIVERY_LANGUAGE_ATTACHMENT_FAILED_TRANSPORT_DSN: "gps://defaults/delivery-language-attachment-failed?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_DELIVERY_LANGUAGE_ATTACHMENT_SUCCEEDED_TRANSPORT_DSN: "gps://defaults/delivery-language-attachment-succeeded?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_DELIVERY_LANGUAGE_ATTACHMENT_TRANSPORT_DSN: "gps://defaults/delivery-language-attachment?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_DELIVERY_PUBLICATION_FAILED_TRANSPORT_DSN: "gps://defaults/delivery-publication-failed?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_FAILURES_TRANSPORT_DSN: "gps://default/failures?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_INTERACTIONS_TRANSPORT_DSN: "gps://default/interactions?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_ITEM_EXTERNAL_SCORE_DSN: "gps://default/grader-manual-results-topic?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_PLAGIARISM_STATUS_TRANSPORT_DSN: "gps://default/plagiarism-status?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_PUBLICATIONS_TRANSPORT_DSN: "gps://defaults/publication?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_RESULTS_TRANSPORT_DSN: "gps://default/result-extraction?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_SCORING_DELIVERIES_TRANSPORT_DSN: "gps://default/grader-publications-topic?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  MESSENGER_SCORING_SUBMISSION_TRANSPORT_DSN: "gps://default/grader-executions-topic?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10"
  PUBSUB_EMULATOR_HOST: "http://pubsub.deps.internal:8432"
  PUBSUB_PROJECT_ID: "emulator-project"
  REAL_TIME_SERVICE_HOST: "http://tao-ce-rt-timers:8080"
  REAL_TIME_SERVICE_SOCKET_URL: "https://community.tao.internal/timers"
  REDIS_CACHE_DSN: "redis://redis.deps.internal:6379"
  REDIS_CACHE_NAMESPACE: "deliver-be-cache"
  REDIS_GCP_TOKEN_CACHE_DSN: "redis://redis.deps.internal:6379"
  TRUSTED_PROXIES: "0.0.0.0/0"
  XDEBUG_MODE: "off"
  XML_RESULT_EXTRACTION_FILE_MIMETYPES: "[\"application/msword\", \"application/vnd.openxmlformats-officedocument.wordprocessingml.document\", \"application/vnd.ms-excel\", \"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\", \"application/vnd.sun.xml.writer\", \"application/vnd.ms-powerpoint\", \"application/vnd.openxmlformats-officedocument.presentationml.presentation\", \"application/pdf\", \"text/plain\", \"application/rtf\", \"text/html\", \"application/vnd.ms-works\", \"application/vnd.oasis.opendocument.text\", \"application/vnd.oasis.opendocument.presentation\", \"application/vnd.oasis.opendocument.spreadsheet\", \"image/tiff\", \"application/postscript\", \"application/x-hwp\", \"application/vnd.apple.pages\"]"