apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/devkit/manifests

images:
  - name: tao/devkit/backend
    newName: quay.io/tao-ce/devkit/backend
    newTag: latest