apiVersion: apps/v1
kind: Deployment
metadata:
  labels: &labels
    tier: backend 
  name: devkit-lti1p3
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
        
      containers:
      - image: tao/devkit/backend
        resources: {}
        name: backend
        envFrom:
        - secretRef:
            name: tao-ce-setup-devkit-lti1p3-env
        volumeMounts:
        - name: devkit-lti1p3-config
          mountPath: /app/devkit/config/packages/lti1p3.yaml
          subPath: lti1p3.yaml
          readOnly: true
        - name: devkit-lti1p3-keys
          mountPath: /app/devkit/config/keys
          readOnly: true
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
      restartPolicy: Always
      volumes:
      - name: devkit-lti1p3-config
        secret:
          secretName: tao-ce-setup-devkit-lti1p3-config
      - name: devkit-lti1p3-keys
        secret:
          secretName: tao-ce-setup-devkit-lti1p3-keys

---
apiVersion: v1
kind: Service
metadata:
  name: devkit-lti1p3
  labels: &labels
    tier: backend
spec:
  selector: *labels
  ports:
  - port: 80
    targetPort: 80
