apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: tao-ce-

labels:
  - pairs:
      app: tao-ce
      component: devkit
    includeSelectors: true
    includeTemplates: true

configurations:
  - backendRefs.yaml

resources:
- ./deploy.yml
- ./secrets/devkit-lti1p3-env.yaml
- ./route.yml

secretGenerator:
- name: devkit-lti1p3-config
  files:
  - ./files/lti1p3.yaml
- name: devkit-lti1p3-keys
  files:
  - ./files/private.key
  - ./files/public.key

configurations:
  - ./backendRefs.yaml
