apiVersion: v1
kind: Secret
metadata:
  name: datastore-worker-env
type: Opaque
stringData:
  ELASTICSEARCH_URL: http://es.deps.internal:9200
  GCP_PROJECT_ID: 'demo-tao'
  FIRESTORE_PROJECT_ID: 'demo-tao'
  IS_GCP_BUCKET_DISABLED: 'true'
  DATASTORE_CONFIG_SOURCE_PATH: '/app/config/'
  PUBSUB_EMULATOR_HOST: 'http://pubsub.deps.internal:8432'
  PUBSUB_TASK_ORCHESTRATOR_TOPIC_NAME: "task-orchestrator-topic"
  DEBUG: 'true'