apiVersion: "v1"
kind: "Secret"
metadata:
  name: "tao-portal-be-env"
stringData:
  # AI_API_URL: "http://tao-ce-tao-ai-api:3000"
  AUTH_SERVER_API_URL: "http://tao-ce-em-auth-server:8080"
  # CLASSIFICATION_API_URL: "http://tao-ce-tao-classification-be:3000"
  # CONTENT_API_URL: "http://tao-ce-tao-content-be:3000"
  DYNAMIC_API_URL: "http://tao-ce-tao-dynamic-query-api:3000"
  ELASTICSEARCH_URL: "http://es.deps.internal:9200"
  FIRESTORE_EMULATOR_HOST: "firestore.deps.internal:8080"
  FIRESTORE_PROJECT_ID: "demo-tao"
  GCP_PROJECT_ID: "emulator-project"
  # GCP_PUBLICATION_BUCKET_NAME: "nextgen-public-dev-geoffrey"
  GCP_PUBSUB_ACTIVITY_LOGS_TOPIC_NAME: "activity-logs-topic"
  GCP_PUBSUB_PAYMENT_STATUS_SUBSCRIPTION_NAME: "payment-api-payment-status-update-subscription"
  GCP_PUBSUB_PORTAL_SESSION_TEMPLATE_NOTIFICATION_TOPIC_NAME: "portal-session-template-notification"
  GCP_PUBSUB_SESSION_NOTIFICATION_SUBSCRIPTION_NAME: "session-notification-subscription"
  GCP_PUBSUB_SESSION_NOTIFICATION_TOPIC_NAME: "session-notification"
  GCP_PUBSUB_START_EXPORT_CSV_TOPIC_NAME: "start-export-csv-topic"
  GCP_PUBSUB_TASK_ORCHESTRATOR_TOPIC_NAME: "task-orchestrator-topic"
  GCP_PUBSUB_USERS_TOPIC_NAME: "users-ds"
  GCP_PUBSUB_USER_EVENTS_TOPIC_NAME: "portal-user-events"
  # HIERARCHY_API_URL: "http://tao-ce-hierarchy-be:3001"
  INTEGRATION_API_URL: "http://tao-ce-tao-integration-api:3000"
  LOG_LEVEL: "trace"
  LTI_PORTAL_AUDIENCE: "https://community.tao.internal/portal-be"
  # MANUAL_SCORING_API_URL: "http://tao-ce-tao-manual-scoring-be:80"
  NOTIFICATION_ENABLED_CHECK_CACHE_TTL_SEC: "60"
  # PAYMENT_API_URL: "http://tao-ce-tao-payments-be:3001"
  # PAYMENT_APP_URL: "https://community.tao.internal/payments"
  PB_FIRESTORE_COLLECTION: "oat-dev"
  PUBSUB_EMULATOR_HOST: "http://pubsub.deps.internal:8432"
  SIDECAR_API_URL: "http://tao-ce-em-auth-server:8888"
  TASK_ORCHESTRATOR_API_URL: "http://tao-ce-tao-task-orchestrator-be:8080"
  # TEMPLATES_API_URL: "http://tao-ce-tao-templates-api:3000"
  TENANT_API_URL: "http://tao-ce-em-tenant-api:3001"
  TESTRUNNER_API_URL: "http://tao-ce-tao-deliver-be:80"