insecure-entitlements = [ "network.host", "security.insecure" ]

debug = true

[dns]
  nameservers = ["127.0.0.11", "8.8.8.8", "8.8.4.4"]

[worker.oci]
  enabled = false

[worker.containerd]
  enabled = true
  namespace = "k8s.io"

[registry."docker.io"]
  mirrors = ["registry.local:5000"]
  http = true
[registry."registry.local:5000"]
  http = true
