apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/simple-reports/manifests

images:
  - name: tao/simple-reports/backend
    newName: quay.io/tao-ce/simple-reports/backend
    newTag: latest