apiVersion: "gateway.networking.k8s.io/v1"
kind: "HTTPRoute"
metadata:
  name: "tao-task-orchestrator-be"
spec:
  parentRefs:
  - name: gateway
    namespace: istio-system
  rules:
  - backendRefs:
    - name: "tao-task-orchestrator-be"
      port: 3000
    matches:
    - path:
        type: "PathPrefix"
        value: "/task-orchestrator-socket"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          replacePrefixMatch: "/"
          type: "ReplacePrefixMatch"
  - backendRefs:
    - name: "tao-task-orchestrator-be"
      port: 8080
    matches:
    - path:
        type: "PathPrefix"
        value: "/task-orchestrator"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          replacePrefixMatch: "/"
          type: "ReplacePrefixMatch"