apiVersion: "v1"
kind: "Secret"
metadata:
  name: devkit-lti1p3-env
stringData:
  APP_DEBUG: "true"
  APP_ENV: "prod"
  APP_HOST: "https://community.tao.internal/devkit/"
  REDIS_CACHE_DSN: "redis://redis.deps.internal:6379"
  XDEBUG_MODE: "off"
  HTTPS: "on"
