apiVersion: apps/v1
kind: Deployment
metadata:
  labels: &labels
    tier: timers
  name: rt-timers
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
        
      containers:
      - image: tao/timers/backend
        resources: {}
        name: timers
        envFrom:
        - secretRef:
            name: rt-timers-env
        ports:
        - containerPort: 3000
          protocol: TCP
          name: socket
        - containerPort: 8080
          protocol: TCP
          name: http
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: rt-timers
  labels: &labels
    tier: timers
spec:
  selector: *labels
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 3000
    targetPort: 3000
    name: socket

---
apiVersion: v1
kind: Secret
metadata:
  name: rt-timers-env
type: Opaque
stringData:
  FIRESTORE_EMULATOR_HOST: "firestore.deps.internal:8080"
  FIRESTORE_PROJECT_ID: "demo-tao"
  LOG_LEVEL: "trace"
  MESSENGER_ASSESSMENT_LOG_TRANSPORT_DSN: "gps://default?client_config[apiEndpoint]=http://pubsub.deps.internal:8432&max_messages_pull=10&topic[name]=assessment-log"
  PUBSUB_EMULATOR_HOST: "http://pubsub.deps.internal:8432"
  PUBSUB_PROJECT_ID: "demo-tao"
  SIDECAR_URL: "http://tao-ce-em-auth-server:8888"
  TIMERS_FIRESTORE_COLLECTION: "oat-dev"
  TIMERS_JWKS_URL: "http://tao-ce-em-auth-server:8080/.well-known/jwks.json"
