
namePrefix: tao-ce-

labels:
  - pairs:
      app: tao-ce
      component: timers
    includeSelectors: true
    includeTemplates: true

resources:
- ./deploy.yaml


configurations:
  - ./backendRefs.yaml

