apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: tao-ce-

labels:
- pairs:
    component: scoring
    app: tao-ce
  includeSelectors: true
  includeTemplates: true

resources:
  - ./deployments/manual-scoring.yaml
  - ./deployments/scoring-service.yaml

secretGenerator:
- name: manual-scoring-static-config
  files:
    - files/Caddyfile
- name: manual-scoring-fe-env
  envs: [ secrets/manual-scoring-fe.env ]
- name: manual-scoring-be-env
  envs: [ secrets/manual-scoring-be.env ]
- name: scoring-service-be-env
  envs: [ secrets/scoring-service-be.env ]
# - name: hbl-scoring-engine-be-env
#   envs: [ secrets/hbl-scoring-engine-be.env ]

configurations:
  - ./backendRefs.yaml
