apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/setup/manifests

images:
  - name: tao/setup/controller
    newName: quay.io/tao-ce/tao/setup/controller
    newTag: latest
  - name: services/pubsub/cli
    newName: quay.io/tao-ce/services/pubsub/cli
    newTag: latest