apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/setup/manifests
  - ./init-pubsub.yaml

images:
  - name: tao/setup/controller
    newName: quay.io/tao-ce/tao/setup/controller
    newTag: latest