apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: jsreport
  name: jsreport
spec:
  selector:
    matchLabels:
      tier: jsreport
  template:
    metadata:
      labels:
        tier: jsreport
    spec:
      containers:
      - image: jsreport/jsreport:4.3.1
        resources: {}
        name: backend
        ports:
        - containerPort: 3000
          protocol: TCP
          name: http
        volumeMounts:
        - mountPath: /app/jsreport.config.json
          name: jsreport-config
          readOnly: true
          subPath: jsreport.config.json
      restartPolicy: Always
      volumes:
      - secret:
          secretName: jsreport-config
        name: jsreport-config
---

apiVersion: v1
kind: Service
metadata:
  name: jsreport
  labels: &labels
    tier: jsreport
spec:
  selector: *labels
  ports:
  - port: 3000
    targetPort: 3000
