apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/task-orchestrator/manifests

images:
  - name: tao/task-orchestrator/backend
    newName: quay.io/tao-ce/tao/task-orchestrator/backend
    newTag: latest