apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/dynamic-query/manifests

images:
  - name: tao/dynamic-query/api
    newName: quay.io/tao-ce/dynamic-query/api
    newTag: latest