apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: tao-stack-autodiscovery
spec:
  generateSelector: true
  parentResource:
    apiVersion: community.taocloud.org/v1alpha1
    resource: taosetup
  childResources:
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: secrets
    updateStrategy:
      method: InPlace
  resyncPeriodSeconds: 30
  hooks:
    sync:
      webhook:
        url: http://tao-setup-controller.metacontroller/sync

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tao-setup-controller
  namespace: metacontroller
  labels: &labels
    app: tao
    component: setup
    tier: controller
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: hooks
        image: tao/setup/controller
        imagePullPolicy: Never
        workingDir: /hooks
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tao-setup-controller
  namespace: metacontroller
  labels: &labels
    app: tao
    component: setup
    tier: controller
spec:
  selector: *labels
  ports:
  - port: 80
    targetPort: 8080