apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/environment-management/manifests

images:
  - name: tao/environment-management/lti-gateway
    newName: quay.io/tao-ce/environment-management/lti-gateway
    newTag: latest
  - name: tao/environment-management/auth-server
    newName: quay.io/tao-ce/environment-management/auth-server
    newTag: latest
  - name: tao/environment-management/sidecar
    newName: quay.io/tao-ce/environment-management/sidecar
    newTag: latest
  - name: tao/environment-management/envoy
    newName: quay.io/tao-ce/environment-management/envoy
    newTag: latest