apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/portal/manifests

images:
  - name: tao/portal/bootstrap
    newName: quay.io/tao-ce/tao/portal/bootstrap
    newTag: latest
  - name: tao/portal/static
    newName: quay.io/tao-ce/tao/portal/static
    newTag: latest
  - name: tao/portal/backend
    newName: quay.io/tao-ce/tao/portal/backend
    newTag: latest