insecure-entitlements = [ "network.host", "security.insecure" ]

root = "/var/lib/buildkit"

debug = true

[grpc]
  address = ["tcp://0.0.0.0:12345"]

[dns]
  nameservers = ["127.0.0.11"]

[worker.oci]
  enabled = false

[worker.containerd]
  enabled = true
  namespace = "k8s.io"
  address = "/run/k3s/containerd/containerd.sock"
  gc = true
  maxUsedSpace = "20GB"
  minFreeSpace = "2GB"

[registry."docker.io"]
  mirrors = ["registry.local:5000"]
  http = true

[registry."registry.local:5000"]
  http = true
