apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    tier: be
  name: tao-deliver-be
spec:
  selector:
    matchLabels:
      tier: be 
  template:
    metadata:
      labels:
        tier: be
    spec:
      initContainers:
      - image: tao/deliver/backend
        resources: {}
        volumeMounts: &volumes
        - name: deliver-data
          mountPath: /app/deliver/var/storage
        name: init 
        envFrom:
        - secretRef:
            name: tao-ce-setup-tao-deliver-be-env
        command:
        - /bin/sh
        - -c
        - |
          true
          # php bin/console messenger:setup-transports
      containers:
      - image: tao/deliver/backend
        resources: {}
        volumeMounts: &volumes
        - name: deliver-data
          mountPath: /app/deliver/var/storage
        name: backend
        envFrom:
        - secretRef:
            name: tao-ce-setup-tao-deliver-be-env
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
      - image: tao/deliver/backend
        resources: {}
        volumeMounts: *volumes
        name: worker
        envFrom:
        - secretRef:
            name: tao-ce-setup-tao-deliver-be-env
        command:
        - /bin/sh
        - -c
        - |
          php bin/console messenger:consume -vvv  publication result-extraction clean-up delivery-language-attachment
      restartPolicy: Always
      volumes:
      - name: deliver-data
        hostPath:
          path: /data/tao/deliver

---

apiVersion: v1
kind: Service
metadata:
  name: tao-deliver-be
  labels: &labels
    tier: be
spec:
  selector: *labels
  ports:
  - port: 80
    targetPort: 80
