apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels: &labels
    tier: scoring-service
  name: tao-scoring-service
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      initContainers:
      - image: tao/scoring/service/be
        resources: {}
        name: init
        envFrom:
        - secretRef:
            name: scoring-service-be-env
        command:
        - /bin/sh
        - -c
        - |
          php bin/console cache:clear -vvv
          php bin/console doctrine:database:create --if-not-exists --no-interaction
          php bin/console doctrine:migrations:migrate --no-interaction
          php bin/console messenger:setup-transports -vvv
        volumeMounts: &volumes
        - name: deliver-data
          mountPath: /app/ss-be/var/storage
      containers:
      # - image: tao/scoring/service/be
      #   resources: {}
      #   name: dispatch
      #   envFrom:
      #   - secretRef:
      #       name: scoring-service-be-env
      #   volumeMounts: *volumes
      #   command:
      #   - /bin/sh
      #   - -c
      #   - |
      #     php bin/console cache:clear -vvv
      #     php bin/console ss:delivery-execution:schedules-dispatch
      - image: tao/scoring/service/be
        resources: {}
        name: worker
        envFrom:
        - secretRef:
            name: scoring-service-be-env
        volumeMounts: *volumes
        command:
        - /bin/sh
        - -c
        - |
          php bin/console cache:clear -vvv
          # sleep infinity
          php bin/console messenger:consume grader-publications grader-scores grader-executions scores submissions ags
      - image: tao/scoring/service/be
        resources: {}
        name: be
        envFrom:
        - secretRef:
            name: scoring-service-be-env
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts: *volumes
      restartPolicy: Always
      volumes:
      - name: deliver-data
        hostPath:
          path: /data/tao/deliver
---
apiVersion: v1
kind: Service
metadata:
  name: tao-scoring-service-be
  labels: &labels
    tier: scoring-service
spec:
  selector: *labels
  ports:
  - port: 80
    targetPort: 80
    name: http


---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: tao-scoring-service-dispatch
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: tao/scoring/service/be
            resources: {}
            name: worker
            envFrom:
            - secretRef:
                name: scoring-service-be-env
            command:
            - /bin/sh
            - -c
            - |
              php bin/console cache:clear -vvv
              php bin/console ss:delivery-execution:schedules-dispatch
          restartPolicy: Never

---