
namePrefix: tao-ce-

labels:
  - pairs:
      app: tao-ce
      component: portal
    includeSelectors: true
    includeTemplates: true

resources:
- ./deployments/be.yaml
- ./deployments/static.yaml
- ./deployments/bootstrap.yaml
- ./routes/tao-portal-bootstrap.yaml
- ./routes/tao-portal-static.yaml


secretGenerator:
  - name: tao-portal-static-config
    files:
    - ./files/Caddyfile

configurations:
  - ./backendRefs.yaml

