apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: be
  name: tao-task-orchestrator-be
spec:
  selector:
    matchLabels:
      tier: be 
  template:
    metadata:
      labels:
        tier: be
    spec:
      containers:
      - image: tao/task-orchestrator/backend
        resources: {}
        name: worker
        envFrom:
        - secretRef:
            name: tao-ce-setup-tao-task-orchestrator-be-env
        command:
        - npm
        - run
        - start:worker
      - image: tao/task-orchestrator/backend
        resources: {}
        name: backend
        envFrom:
        - secretRef:
            name: tao-ce-setup-tao-task-orchestrator-be-env
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        - containerPort: 3000
          protocol: TCP
          name: socket
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: tao-task-orchestrator-be
  labels: &labels
    tier: be
spec:
  selector: *labels
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 3000
    targetPort: 3000
    name: socket
