apiVersion: v1
kind: Secret
metadata:
  name: tao-hierarchy-be-env
stringData:
  DEBUG: '1'
  LOG_LEVEL: 'debug'
  NODE_ENV: 'production'
  PORT: '3001'
  ELASTICSEARCH_URL: http://es.deps.internal:9200
  ELASTICSEARCH_PREFIX: ''
  LOG_TYPE: 'file'
  SIDECAR_API_URL: http://tao-ce-em-auth-server:8888
  DYNAMIC_API_URL: http://tao-ce-tao-dynamic-query-api:3000
  GCP_PROJECT_ID: demo-tao
  GOOGLE_CLOUD_PROJECT: demo-tao
  GCLOUD_PROJECT: demo-tao
  FIRESTORE_ROOT_COLLECTION: 'oat-dev'
  FIRESTORE_ROOT_DOC: 'stores'
  FIRESTORE_HIERARCHY_BE_COLLECTION: 'hierarchies'
  FIRESTORE_EMULATOR_HOST: "firestore.deps.internal:8080"
  FIRESTORE_PROJECT_ID: "demo-tao"