apiVersion: v1
kind: Secret
metadata:
  name: tao-task-orchestrator-be-env
stringData:
  ADMIN_CLIENT_SECRET: "secret"
  AUTH_SERVER_API_URL: "http://tao-ce-em-auth-server:8080"
  DEBUG: "true"
  DYNAMIC_API_URL: "http://tao-ce-tao-dynamic-query-api:3000"
  ELASTICSEARCH_URL: "http://es.deps.internal:9200"
  EMAIL_SUBSCRIPTION_PORTAL_DOMAIN: "community.tao.internal"
  EMAIL_SUBSCRIPTION_TOKEN_SECRET: "verySecretString"
  FIRESTORE_EMULATOR_HOST: "firestore.deps.internal:8080"
  FIRESTORE_PROJECT_ID: "demo-tao"
  FIRESTORE_DATABASE_ID: "default"
  NODE_CONFIG: production
  NODE_ENV: production
  GCP_PROJECT_ID: "demo-tao"
  GCP_PUBSUB_EMAIL_SERVICE_TOPIC_NAME: "tao-templates-email-topic"
  GCP_PUBSUB_TASK_ORCHESTRATOR_SUBSCRIPTION_NAME: "task-orchestrator-ds"
  GCP_PUBSUB_TASK_ORCHESTRATOR_TOPIC_NAME: "task-orchestrator-topic"
  JWKS_URL: "http://tao-ce-em-auth-server:8080/.well-known/jwks.json"
  LOG_LEVEL: "trace"
  PORT: "8080"
  PUBSUB_EMULATOR_HOST: "http://pubsub.deps.internal:8432"
  SIDECAR_API_URL: "http://tao-ce-em-auth-server:8888"
  SOCKET_PORT: "3000"
  TASK_ORCHESTRATOR_FIRESTORE_COLLECTION: "oat-dev"
  TASK_ORCHESTRATOR_FIRESTORE_STORAGE: "task-orchestrator-storage"
  # TENANT_API_URL: "http://tao-ce-em-tenant-api:3001"