apiVersion: v1
kind: Secret
metadata:
  name: auth-server-env
stringData:
  ACCESS_TOKEN_TTL: "3600"
  APP_PRIMARY_KEY_KD: "primaryKeyPair"
  APP_PRIVATE_KEY_PASSPHRASE: "123456"
  APP_PRIVATE_KEY_PATH: "/app/dist/config/keys/private.pem"
  APP_PUBLIC_KEY_PATH: "/app/dist/config/keys/public.pem"
  CC_USER_DATA_PRELOADER_SOURCE_PATH: "/app/preload-data/"
  CORS_ALLOW_ORIGIN: "*"
  DEBUG: "true"
  ELASTICSEARCH_PREFIX: ""
  ELASTICSEARCH_URL: "http://es.deps.internal:9200"
  EM_FIRESTORE_COLLECTION: "oat-dev"
  EM_SIDECAR_HOST: "tao-ce-em-sidecar"
  # ENABLE_LOCAL_FILE_CONFIG: "true"
  ENV: "d0"
  FIRESTORE_EMULATOR_HOST: "firestore.deps.internal:8080"
  FIRESTORE_PROJECT_ID: "demo-tao"
  GCP_PROJECT_ID: "demo-tao"
  GCP_PUBSUB_TASK_ORCHESTRATOR_TOPIC_NAME: "task-orchestrator-topic"
  GRPC_PORT: "1888"
  HIERARCHY_API_URL: "http://tao-ce-hierarchy-be:3001"
  HTTP_GRPC_GATEWAY_PORT: "8888"
  JWT_CLAIM_ISSUER: "tao-ce-em-auth-server"
  LTI1P3_SERVICE_ENCRYPTION_KEY: "235539604521e196010282fa6cf9b349"
  MANUAL_SCORING_URL: "http://tao-ce-tao-manual-scoring-be:8080"
  NAMESPACE: "oat-dev"
  NODE_ENV: "production"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  PORT: "8080"
  PORTAL_REPORT_LOCALES: "en-US es-ES fr-FR"
  PUBSUB_EMULATOR_HOST: "http://pubsub.deps.internal:8432"
  PUBSUB_PROJECT_ID: "demo-tao"
  REDIS_CACHE_DSN: "redis://redis.deps.internal:6379"
  REFRESH_TOKEN_TTL: "86400"
  TENANT_DATA_PRELOADER_SOURCE_PATH: "/app/preload-data/"
