apiVersion: v1
kind: Secret
metadata:
  name: lti-gateway-env
stringData:
  APP_ENV: "dev"
  APP_SECRET: "5c796f2ca45012243a63d55d9f78771d"
  EM_AUTH_SERVER_GRPC_GATEWAY_HOST: "http://tao-ce-em-auth-server:8888"
  EM_SIDECAR_HOST: "tao-ce-em-auth-server"
  EM_SIDECAR_PORT: "1888"
  # GOOGLE_APPLICATION_CREDENTIALS: "/var/storage/gcp/key.json"
  GOOGLE_CLOUD_PROJECT: "demo-tao"
  GCP_PROJECT_ID: "demo-tao"
  GOOGLE_CLOUD_SUBSCRIPTION_WORKER: "lti-events-subscription"
  LTI1P3_SERVICE_ENCRYPTION_KEY: "3feca5c091026487889a20e5a7ddd98e"
  MESSENGER_FAILED_QUEUE_SUBSCRIPTION: "failed-subscription"
  MESSENGER_FAILED_QUEUE_TOPIC: "failed-topic"
  MESSENGER_LTI_EVENTS_QUEUE_SUBSCRIPTION: "lti-events-subscription"
  MESSENGER_LTI_EVENTS_QUEUE_TOPIC: "lti-events-topic"
  PUBSUB_EMULATOR_HOST: "pubsub.deps.internal:8432"
  PUBSUB_PROJECT_ID: "demo-tao"
  SANCTUARY_VERBOSE: "true"
  WORKER_PHP_COMMAND: "php -d memory_limit=-1 /var/www/html/bin/console worker:lti-event"

