apiVersion: v1
kind: Secret
metadata:
  name: sidecar-env
stringData:
  DISABLE_PARTITIONED_COOKIES: "true"
  FF_ENABLE_OFFLINE_MODE: "true"
  FF_ENABLE_SIDECAR_GRPC: "true"
  FF_ENABLE_SIDECAR_GRPC_CONFIG_SERVICE: "true"
  FF_ENABLE_SIDECAR_GRPC_ENVOY_FEATURE_FLAG_FILTER: "true"
  FF_ENABLE_SIDECAR_GRPC_FEATURE_FLAG_SERVICE: "true"
  FF_ENABLE_SIDECAR_GRPC_LTI_SERVICE: "true"
  FF_ENABLE_SIDECAR_GRPC_OAUTH2_SERVICE: "true"
  FF_ENABLE_SIDECAR_HTTP: "true"
  FF_ENABLE_SIDECAR_HTTP_CONFIG_API: "true"
  FF_ENABLE_SIDECAR_HTTP_FEATURE_FLAG_API: "true"
  FF_ENABLE_SIDECAR_HTTP_LTI_API: "true"
  GRPC_VERBOSITY: "debug"
  LOG_LEVEL: "debug"
  REDIS_ADDRESS: "redis.deps.internal:6379"
  REDIS_DB: "0"
  SIDECAR_ENVOY_FILTER_AUTH_SERVER_URL: "http://tao-ce-em-auth-server:8080"
  SIDECAR_ENVOY_FILTER_FRONTEND_URL: "https://community.tao.internal/deliver-fe,https://community.tao.internal/deep-linking,https://community.tao.internal/ms-fe,https://community.tao.internal/pr-fe"
  SIDECAR_ENVOY_FILTER_JWKS_URL: "http://tao-ce-em-auth-server:8080/.well-known/jwks.json"
  SIDECAR_ENVOY_FILTER_LTI_HANDLER_URL: "http://tao-ce-em-auth-server:8080/v1/lti/validate-platform-launch"
  SIDECAR_ENVOY_FILTER_REFRESH_TOKEN_URI: "/api/v1/auth/refresh-tokens"
  SIDECAR_ENVOY_FILTER_REQUEST_HEADER_PREFIX: "X-OAT-CUSTOM-"
  SIDECAR_ENVOY_FILTER_REQUEST_HEADER_TENANT: "X-OAT-TENANT-ID"
  SIDECAR_ENVOY_FILTER_TOKEN_URL: "http://tao-ce-em-auth-server:8080/v1/oauth2/tokens"
  SIDECAR_GRPC_PORT: "18084"
  SIDECAR_HTTP_PORT: "8080"
  SIDECAR_PRIVATE_KEY_PASSPHRASE: "123456"
  SIDECAR_PRIVATE_KEY_PATH: "/var/keys/private.pem"
  SIDECAR_PUBLIC_KEY_PATH: "/var/keys/public.pem"
