apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/datastore/manifests

images:
  - name: tao/datastore/worker
    newName: quay.io/tao-ce/tao/datastore/worker
    newTag: latest